library(rvest)
library(dplyr)
library(robotstxt)
library(stringr)
link="https://www.autocarindia.com/new-cars"
path=paths_allowed(link)
web=read_html(link)
name=web %>% html_nodes(".heading-h4 a")%>% html_text()
View(name)
price=web %>% html_nodes(".price-model")%>% html_text()
View(price)
mileage=web %>% html_nodes(".mob-border-bottom~ .mob-border-left+ .mob-border-bottom .icon-name+ p")%>% html_text()
View(mileage)
fueltype=web %>% html_nodes(".mob-border-bottom:nth-child(2) .icon-name+ p")%>% html_text()
View(fueltype)
aru.bu<-data.frame(name,price,mileage,fueltype)
write.csv(aru.bu,"cars.csv")
